### ISSUE TITLE
I am looking for the part 2 of your article on developer.amadeus.com.

### ISSUE THREAD

**Issue by stephenmorton** [Samuel-2626/flight-booking-backend#1]
Hi, i have read your part 1 which looks like a really good article thus far, but cannot find the part 2. Part 1 is here https://developers.amadeus.com/blog/flight-booking-app-angular-1
But I cannot find part 2. Appologies if I missed it, or is hasn't been posted yet.
Steve

**Comment by Samuel-2626** [comment]
Hi @stephenmorton, thanks for taking time to read through. Yeah, it hasn't been posted.

**Comment by Samuel-2626** [comment]
Hey @stephenmorton , checked of recent. It's been published. 

https://developers.amadeus.com/blog/flight-booking-app-angular-2

**Comment by stephenmorton** [comment]
Thanks Samuel, yes, I have seen it.

Stephen Morton
Manager
Total Telco Group Pty Ltd

***@***.***
02 8488 3150<tel:02%208488%203150> | 0418 111 068<tel:0418%20111%20068>
***@***.***
www.totaltelco.com.au<https://www.totaltelco.com.au/>
